name: Deploy to GCS

on:
  push:
    branches:
      - main

env:
  BUCKET_NAME: spark-datasets-kds
  CODE_SUBDIR: products/py_modules

jobs:
  push-to-gcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/542207008114/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-deployer@project-b33d6da0-bcfc-471f-99c.iam.gserviceaccount.com"

      - name: Set up gcloud & gsutil
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gsutil

      - name: Ensure GCS path exists
        run: |
          gsutil ls gs://$BUCKET_NAME/$CODE_SUBDIR || gsutil mkdir -p gs://$BUCKET_NAME/$CODE_SUBDIR

      - name: Download pydeequ wheel
        run: |
          python -m pip install --upgrade pip
          mkdir -p wheels
          pip download pydeequ --only-binary=:all: --no-deps -d wheels
          ls -l wheels

      - name: Upload pydeequ wheels to GCS
        run: |
          ls wheels/*.whl >/dev/null 2>&1 && \
          gsutil cp wheels/*.whl gs://$BUCKET_NAME/$CODE_SUBDIR || \
          (echo "No wheels found!" && exit 1)

      - name: Upload Python modules to GCS
        run: |
          gsutil -m cp \
            src/deequ_checks.py \
            src/etl.py \
            src/spark_builder.py \
            src/writer.py \
            gs://$BUCKET_NAME/$CODE_SUBDIR

      - name: Upload main.py to GCS
        run: |
          gsutil cp src/main.py gs://$BUCKET_NAME/products/main.py